### ISSUE TITLE
DNS 泄漏可能比你想的范围广以及 clash 配置 & clash 与 tailscale 共同使用的配置

### ISSUE THREAD

**Issue by meooxx** [meooxx/blog#31]
# DNS 泄漏
- [定义 DNS 泄漏](#dns-泄漏)
- [公共 DNS 和 Doh 会是最优解吗](#公共-dns-和-doh-会是最优解吗)
- [方案最优解](#方案最优解)
- [具体配置分析(clash)](#具体配置解析)
- [重中之重-规则集配置](#重中之重-规则集配置)
- [浅谈第二种的 DNS 防泄漏](#浅谈第二种的-dns-防泄漏)
- [另外小的细节](#另外小的细节)
- [tailscale 与 clash tun 模式冲突](#tailscale-与-clash-tun-模式冲突)
- [懒人福音, 纯手工打造的 clash 配置](#懒人福音-匠人纯手工打造的-clash-配置和规则)

什么是 DNS 安全, 有的人认为是域名查询不经过国内的 DNS 服务器就是安全, 或者不被目标网站检测出非代理服务器的地址或者真实 ip 的上游DNS. [wiki说法](https://en.wikipedia.org/wiki/DNS_leak)
> A DNS leak is a security flaw that allows [DNS](https://en.wikipedia.org/wiki/DNS) requests to be revealed to [ISP](https://en.wikipedia.org/wiki/ISP) DNS servers, despite the use of a [VPN](https://en.wikipedia.org/wiki/VPN) service to attempt to conceal them.[[1]](https://en.wikipedia.org/wiki/DNS_leak#cite_note-1) Although primarily of concern to VPN users, it is also possible to prevent it for [proxy](https://en.wikipedia.org/wiki/Proxy_server) and direct internet users.    

 我认为应该按照需要防止的对象来定义, 第一: **防止在本机发起的对敏感域名的解析被第三方探测到, 尤其是运营商或者帽子👮,** 一旦泄漏, 被捕获到查询记录是非常容易的. 且目前的科学上网生态主要是 clash like 核心为主的客户端, 且因为无意识错误的规则集配置可能导致非常广范围的 DNS 泄漏. 不管你是否使用了国外 **DNS 或者 Doh/Dot服务.** 

第二种: 如果你是防止目标网站检测出你正在使用代理服务, 那 DNS 泄露就是目标网站主要因为你的 DNS 查询行为, 从而检测到了和你正在使用的代理服务器的 ip 不同区域的 ip, 或者是不合理的上游 DNS 的 ip. 尤其是 netflix 或者 chatGTP等约束使用地的一些服务. 简单举例来说, 通过新加坡的 vps 访问 netlfix时, 被 neflix 发现, 你会用上海的或者其他任何不同于新加坡的 ip 访问别的域名 或者使用不在新加坡的 DNS 服务器解析了 netflix 的其他域名.

本文则重讨论的是第一种, 因为第二种没有安全疑虑, 且以下讨论情况均指第一种.   
目前第一种泄漏的检测倒是很好检查, 只需要打开 `wireshark` 或者其他可以捕获 upd 协议的抓包工具, 按 `dns` 去过滤记录,  **然后访问需要代理的网站**. 如果列表中出现了**对应敏感域名的 DNS 查询记录, 则你目前的网络环境 DNS 查询是完全泄漏的. **换句话说就是, 中间人可以很轻易的捕获到你当前网络环境下的 DNS 查询, 根据你暴露的 DNS 记录, 中间人完全知道你在访问哪些具体敏感网站, 并且知道你在进行科学上网**. 
此时的列表只应该出现非敏感域名的查询记录才是正常的**(没有配置 Doh 情况下), . 查看图 1.1

显然只**使用国外的域名解析服务或者简单使用代理工具的全局模式**是不能万事大吉的. 尤其是在和 clash/mihomo(以下 clash 或者 mihomo 均指 clash 等类似内核)内核下的客户端结合使用的时候, 情况将变得稍微有点复杂.   
当然这里不用 `ipleak.net` 等网站的测试结果作为参考依据. 因为基于上面第一种定义来说, 不敏感的域名查询被**第三方**捕获到是无关紧要, 尤其是科学上网场景. （这里的第三方指的是任意中间人）因为其他那些国内的普通域名在国内被访问是天经地义, 没人会怀疑, 且应该选用解析响应最快的 DNS 服务器.   

当然你介意被中间人看到你的解析记录, 也可以搭配 Doh(注意以下 Doh, 包含 Dot, 俩者类似. 一个基于 https, 一个基于 tls) 来使用, 当然理想情况下这里的 Doh 按照内核的逻辑也只该用来解析代理规则之外的域名, 通常为那些国内域名.  

## 为什么你用了国外的 DNS 不是万事大吉? 
常规来讲, 使用国外大厂 DNS 服务如`8.8.8.8` 或者 `1.1.1.1`, 主要是为了解决 DNS 污染的问题. 泄漏的问题主要还是因为 DNS 查询是基于 UDP 协议的, 通常在53端口, 所以很轻易被第三方捕获到. 下图所示

<img width="860" alt="Image" src="https://github.com/user-attachments/assets/69f200f1-9021-41f3-be05-ba78fefef327" />  
图 1.1  

在这里, 虽然用了谷歌的 dns 解析, 可以保证解析结果无污染返回的地址是正确. 但是这里的解析请求会被中间人看的一清二楚, 比如图示这里查询的 `google.com`.  这无异于裸奔. 如果被叔叔利用, 轻则相安无事, 或者短信警告, 重则喝茶.  

##  公共 DNS 和 Doh 会是最优解吗? 

答案显然不是, 首先普通公共 DNS 没有解决上面被监控的问题, 并且目前国内的主流 DNS 服务比如 DNSPod 或 Alibaba 的 DNS 都有多个节点, 虽然都支持 Doh, 但是明显的是他们速度肯定不如本地运营商的解析速度的.  

拿 DNSPod 举例, 他们的入口服务器肯定在你的城市的周边, 但是很多时候他们处理这次查询的服务器不在你的周围城市, 比如你的查询请求到了南京的服务器, 具体处理这次查询是他们在广州的服务器, 虽然他们内部服务器之间传输很快, 但也确实导致查询相对变慢. 更别说使用他们的 Doh 服务了.   

我这里只大概阐述为什么公共 DNS 不是最优解的原因, 具体的原因和证明请查看[使用公共 DNS 上网的弊端（一）](https://ephen.me/2017/PublicDns_1/)这篇文章. 

其次虽然使用 doh 可以规避监控, 正如我说的 doh 也不是万能, 它有另外一个问题, 当配合 clash 使用的时候, **如果你在clash 配置的规则错误, 然后又全部用了 Doh 解析, 可能会导致部分 domain 匹配规则失效**  

具体在后面讨论 clash 规则配置的时候我会详细解释. **而且 `clash-verge` 客户端给出的 DNS 默认覆写配置有很大问题**
所以, 我们要尽可能合理分流域名和配置规则. 不能期待一个简单方法解决所有问题. 

这里有人会问, 这里是不是说法矛盾了, 又要安全, 又要, 又不要的使用国内 DNS. 尤其是运营商的 DNS  服务?
  
是也不是,  因为我们在意的是解析国外代理域名的时候不被发现或者监听. 而国内的一些常见域名解析如微信, 抖音之类的, 想要知道的人(尤其帽子)知道也无妨, 当然你要是也在意这些查询的隐私, 可以选择 Doh 牺牲掉一些速度换安全(当然也不是绝对安全, 国内 Doh 服务几乎可以断定会记录查询记录, 虽然这里可以依赖国外的 Doh 服务).  

## 方案最优解
按照目前 mihomo 的思路策略(即在配置正确的前提下, 后面详细说明错误场景): 发现需要代理的域名则不对其域名进行解析, 此时是直接转发给代理服务器, 由代理服务器解析和访问. 其他的国内域名解析, 则应配置对应的国内 DNS 来解析, 而用于处理代理请求的服务器, 其本身的域名也应被单独配置的 proxy-nameserver 解析. 

而 Doh 的理想场景应该只严格限制在解析国内域名(对国内域名配置的话)和有限的代理服务器域名(应该配置)的俩种场景

具体按 clash/mihomo/meta 的配置来说 default-server 应配置为国内的 DNS,  且必须是类似`233.5.5.5` 或者 `system` 这类的非 Doh 的 ip, 只用来解析配置在 nameserver 的 doh 服务的域名(这里有点绕, 简单来说 Doh 是依托 https 协议来解析域名, 所以在使用其服务解析其他域名之前, 需要先解析 Doh 服务的域名😂😂).   nameserver 配置的公共 DNS 只用来解析非需要被代理请求的域名比如国内域名, 理想情况应使用本地运营商 DNS 保证相对快的解析速度(⚠️前提这里 rule 配置必须正确,  否则大概率有 DNS 泄漏, 后面会说), 当然这里为了安全可以选择使用 Doh 服务如`https://doh.pub/dns-query`, 而 proxy-nameserver 则只用来解析代理服务器其本身的域名, 也就是订阅配置里面的每一项中的 hostname. 可以配置为国内的 Doh, 如有更安全的要求可以配置国外 Doh.  

当然所有的一切都是在**配置正确**的前提下, 才会按照理想设计进行.  下面我还会具体聊具体错误配置, `重点批评 clash-verge 给的 dns 默认配置`. 

## 具体配置解析
只谈 TUN 的 fake-ip 模式, 其他模式没必要谈对吗😂   
先骂 clash-verge, 这里只贴需要改动的配置和必要配置
```yaml
#  这里是 clash-verge 给出默认覆写配置, 重点批评, 请查看 nameserver 项
dns:
  # ...省略无关配置
  enhanced-mode: 'fake-ip'
  nameserver:
    - '8.8.8.8'                       #  ??? 这行是什么鬼
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'

```
这里唯一的败笔, 就是加了一个 `8.8.8.8`的 dns 域名配置. 因为总共配置了三个 DNS  服务器, 所以内核在需要解析域名的时候, 会同时发三个dns请求, 分别向 `8.8.8.8` 和 其他俩个 Doh 查询域名. 这里发向 `8.8.8.8` 的查询就会把这次查询记录暴露, 那另外俩个 Doh 查询的就无意义了.  
所以这里如果想用 Doh 应该要把 `8.8.8.8` 去掉; 如果可以接受不使用 Doh, 也应该把其他俩个 doh 换成 `233.5.5.5` 这类的 ip 或者 system, 最起码可以让查询更快. clash-verge 的问题, **他这里的配置放在覆写的默认配置上, 就算机场提供的配置是正确的, 用户在 verge 的客户端上如果开启了覆写, 就会将原本正确的改成错误的.** 所以说这个默认配置可能导致了部分 DNS 泄漏.

**⚠️如果用户配置规则错误, 手动配置的时候非常常见，尽管可能在很熟悉规则的情况下，也大可能发生的错误，如 ip 集忘了加 no-resolve 或者中间混杂了 classical 类的规则, 就会导致了解析了原本不该解析的代理域名, 此时nameserver 如果配置了非 Doh, 则会导致查询敏感域名泄漏. 但如果只配置了 Doh 即使规则配置错误, 虽不会导致泄漏, 算是 nameserver 使用 Doh 的一个好处(当然配置错误就会有坏处, 后面具体讨论), 但可能会导致匹配规则的失效和冗余 DNS 查询**

<img width="1187" alt="Image" src="https://github.com/user-attachments/assets/2d91908a-ec1b-4299-98bb-51b2d8ae8543" />

## 重中之重-规则集配置
常用但是几乎每个人都会犯错的地方, 如果错误轻则导致策略实效, 重则有 DNS 泄漏危险

现在 mihomo 提供了大而全而美的规则配置数据库, 托管在 github [metacubex/meta-rules-dat](https://github.com/MetaCubeX/meta-rules-dat)上, 很多人就不知道也没意识到有这个数据库.   
第二个用户没空去读配置文档, 只想当然按照以往惯性方式来配置.   
或许也不能全部责怪用户, 因为之前的生态太丰富了比如 shadowrocket, surge 等之前都是懒人配置, 别人配置好了规则直接引用就好了, 这也导致目前 clash/mihomo 规则集配置错误百出. 

先聊一下之前的生态的配置文件比如 shadowrocket 的神机规则, 都是一个大而美的规则集, 将 ip 规则 和 domain 规则融合在一起了.  但是这种形式规则在 mihomo 内核这里就不适用了. 为了性能考虑, mihomo 官方在上面数据基础上集中并详细分开了 ip 规则和域名规则, 尽可能的给出了所有细分规则. 感谢 mihomo, mihomo 太伟大了.   
尽管官方兼容以前那种域名和 ip 写一起的规则集, **但正是这种配置大概率导致泄漏 DNS 查询**

主要因为IP 与 domain混用导致, 即使我之前研究了好几天已经觉得搞懂了, 配置的时候还是不注意出错了好几次.   
在开始之前, 还是必须了解并理解这个 DNS 分流流程, 才会知道为什么不能混用, 否则极大概率导致DNS泄漏.   
这里赘述一下内核分流匹配策略的逻辑.  比如访问 google.com, 会去 rules 中查找规则, 如果发现 rule-set 第一行有域名的规则, 且匹配上了, 就会终止匹配进入到对应策略组出站.   
**重点是如果这条域名规则集没有匹配上, 则会使用下一个规则集, 如果下一个规则集是 ip 集, 且没有指定 `no-resolve`, 内核此时就会使用 nameserver 中的配置, 将该域名 如 youtube.com 解析成 ip 地址再进行匹配, 如果 nameserver 中配置了非 doh, 则这条 dns 查询就会泄漏. 这里再次点名一下 clash-verge**
最简单举例如下: 
```yaml

## ⚠️错误示范配置
rules:
  - RULE-SET,apple_domain,_ Apple
  - GEOIP,private,🎯 全球直连,no-resolve                  # ❗️❗️
  - RULE-SET,google_domain,🚀 默认代理
  - MATCH,🐟 漏网之鱼
```
具体简单举例来说, 这里 youtube.com 在第一个rule-set中没匹配到, 则进入第二条 rule-set, 此时发现是 ip 集, 就会用 nameserver 中配置的 DNS 将 youtube.com 域名解析成 ip 再进行匹配.   
**如果 nameserver 配置了非 doh 如 8.8.8.8, 本地就会去该 DNS 查询, 就会导致油管域名查询的泄漏.**  

有小聪明会说那我直接在 nameserver 中使用 Doh 一劳永逸得了. 这就是我前面埋的一个伏笔. 还是上面的配置来说明, 假如此时你自作聪明只配置了 Doh, 那匹配到第二条的时候就会用 Doh 解析油管的域名, 用该 ip 来进行下面的匹配. 那此 ip 集后面的任何域名匹配规则都不会生效.   
如图1.2所示, 即使我在 ip 后面配了一个 google_domain 的规则也没有命中, 最后被 MATCH 捕获.  
所以一定要记住 **ip 匹配集在中间时候一定要加 no-resolve, 且使用的规则集一定要 ip 和 domain 分开**, 或者将ip匹配集挪到最后面.   
**如果想在 clash-verge 复现这个流程一定要改完配置后, 更新一下规则集, 重启内核客户端, 切换代理模式, 开关TUN模式等等, 否则不能立即看到效果. 最终的错误的结果就是 log 里面全是 ip 信息的匹配, 域名策略组几乎全部失效**
**即使做了上述动作, 也不保证立即复现生效, 因为懒得再继续测试其更新的时机或者条件了, 每次等到错误配置配置生效或者正确配置生效都要花很长时间.**

<img width="1176" alt="Image" src="https://github.com/user-attachments/assets/a582f129-c216-4481-8473-c621e15b04e2" />

## 浅谈第二种的 DNS 防泄漏

如果出口的代理节点的 IP 干净的话能解决大部分的问题. 可以选择优质线路机场或加家庭 ip. 另外就是收集全目标网站的域名和 ip 尽可能的全的走代理, 否则直接全局模式也是很好的选择. 

## 另外小的细节
如果是 window 用户, 需要关闭 `智能多宿主名称解析` 策略组. 因为这个策略组会自动发送本机 DNS 解析, 导致前面的配置功亏一篑.   
 另外请使用 `https://browserleaks.com/webrtc` 查看 `webrtc` 是否泄漏了 DNS

## 针对广大只使用机场提供的配置的用户
这类用户普遍来说不懂配置, 不关心配置, 没有自定义配置的需求.   
都是用机场提供的订阅地址, 实地看了一下用的最多的 ACL 配置规则, 发现配置是正确的, 简单将所有域名或者地址一条一条罗列出来的, 没啥问题就是 yaml 文件行数太多太长, 但用起来问题也不大.   

用户只需要关心客户端尤其是 clash-verge 的客户端, DNS 覆写那里就行了.   
如果使用订阅链接去管理配置, 想简单实现 DNS 防泄漏并且国内也要走 Doh, **一定要去掉 nameserver 中默认配置 `8.8.8.8`**, 或者不在意国内的域名的 DNS 查询泄漏可以将覆写的 DNS 配置全部使用 `233.5.5.5` 或者 'system'.   
在轻度使用下, 这样的最简单配置可以最大程度保证没问题. 

但是一但有自定义配置需求的时候, 比如添加策略组, 增加规则集, 添加额外的订阅链接地址的, 这种方式就不适合了.  

这时一定要注意结合 mihomo 的相关文档来看. 了解理解了整个 DNS 解析过程再配置, 保证尽可能安全.  这里也给出最简单配置: 
* **nameserver 中直接只配置 Doh 类型的 DNS, 然后配置里面的关于 ip 规则, 或者混合规则都尽量放到最后. 这样能保证, 规则可能不是最有效, 但是 DNS 不会泄漏.**

* **如果想高效配置规则集, 需严格按照 domain 和 ip 集分开, ip 需要添加 no-resolve,  去掉重复的规则. 搞懂 clash 等内核 DNS 解析流程, 并设置合适的 nameserver 等.**  
本文最后有配置参考

## tailscale 与 clash tun 模式冲突
有 tailscale 的需求, 在 macos 使用会有冲突, 可能因为 tailscale 也是通过 TUN 劫持流量, 并在本地自建 MagicDNS 服务解析网络内主机名.   
这会直接导致和 clash 的冲突, 上不了网. 要不然就是 ip 段冲突比如与其他 VPN 客户端.   

不完美但是简单解决方案一: 即不使用 tailscale 本地的DNS, 缺点就是 tailscale 分配给你的 主机名.tsXXXX.ts.net, 和主机名 无法直接本地使用. 如连接在 tailscale 网络中主机名为openwrt,  使用 ssh openwert 或者 ssh openwrt.tsXXXX.ts.net 均失效. 不过这也能接受, 可以直接使用分配的内网地址, 也不是很麻烦  

不完美略折腾解决方案二, 在宿主机上 docker 里面跑 tailscale + socks5 的服务. 用官方镜像+microsocks 新 build 一个镜像运行.   
好处是不侵犯宿主机配置, 洁癖患者福音. 原理是docker中跑 tailscale + socks5代理服务, 这个代理服务用于将宿主机上的流量代理到容器内 tailscale 网络中.   
因为宿主机无法直接与容器内服务通信, 所以额外需要一个socks5的代理.   
还有一个选择就是官方支持的 userspace networking 模式, 这个模式相当于 socks5/http 一个普通代理服务, 缺点是不支持 TUN 模式, 性能上不如 TUN. 但也是可接受.  

如果选择自己 build 镜像 + socks5 的方式, 不完美的点就是通过容器内网络访问不了宿主机.   
只适合单向穿透的需求, 比如只在工作机器单向回家的场景. dockerfile 和 compose 文件如下
dockerfile
```
FROM tailscale/tailscale:latest
# Install build dependencies
RUN apk add --no-cache git build-base

# Build microsocks from source
RUN git clone https://github.com/rofl0r/microsocks.git && \
    cd microsocks && \
    make && \
    make install && \
    cd .. && rm -rf microsocks
# 启动 tailscaled + 登录 + 启动 SOCKS5

CMD ["/bin/sh", "-c", "\
  tailscaled --state=/var/lib/tailscale/tailscaled.state & \
  sleep 3 && \
  tailscale up --accept-routes && \
  microsocks -p 1080 \
"]
```
compose 文件
```yaml

services:
  
  tailscale-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: tailscale-proxy
    hostname: tailscale-nginx
    
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    ports:
      - "127.0.0.1:1080:1080"   # 仅本地可访问 SOCKS5
```
最后搭配 Clash 配置将 Tailscale 使用的内网网段分流到该容器的 SOCKS5。  

`完美方案` [参考模版](https://gist.github.com/meooxx/5d6e17e186adec975e0ae2b8a577de59): 需要在 clash 配置三处分别是 tun, dns 和 rules
```
省略中间其他无关配置
tun:
  # 排除 tailscale 网段
  route-exclude-address:
    - 100.64.0.0/10
    - 100.100.100.100/32
    - fd7a:115c:a1e0::/48
 

# 省略中间其他
dns:    
# 用nameserver-police指定 tailscale 网段使用 tailscale的本地 quad100 解析
 nameserver-police:
    +.tail{xxxx}.ts.net: 100.100.100.100 # 替换成你的 tailscale domain
 fake-ip-filter:
   #...忽略其他
    - '*.tailscale.com'
    - '*.tailscale.io'
    - '*.ts.net'

# 省略中间其他
# 在 rule 中配置对应网段 DIRECT 或者分流到自定义 tailscale 分组中
rules:
  # tailscale 内网穿透规则, 必须 no-resolve 否则会使用 nameserver dns 查询
  - IP-CIDR,100.100.100.100/32,DIRECT,no-resolve
   - IP-CIDR,10.100.0.0/16,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,fd7a:115c:a1e0::/48,DIRECT,no-resolve
  - DOMAIN-SUFFIX,tailscale.com,🌈 tailscale
  - DOMAIN-SUFFIX,tailscale.io,🌈 tailscale
  # 替换自己的tailscale sub-domain
  - DOMAIN-SUFFIX,tail{0x12345}.ts.net,🌈 tailscale
  - DOMAIN-SUFFIX,这里替换为你的tailscale节点名称如tsXXXX.ts.net,🌈 tailscale
  - DOMAIN-SUFFIX,ts.net,🌈 tailscale
    
```
这样可以完美让 tailscale 和 clash tun 模式共存, 几乎完美支持 MagicDNS(可以看下面的模版)

## 懒人福音, 匠人纯手工打造的 clash 配置和规则  

[宇宙内都好用的clash配置模版](https://gist.github.com/meooxx/5d6e17e186adec975e0ae2b8a577de59)  
模版的优势: 
* **支持多个订阅地址**, 订阅地址来源可以是多个自购机场+自建机场.  不需要多个 profile 文件, 使用的时候无需费劲又麻烦切换 profile . all in one, 所有的订阅/规则集支持自动更新. 规则集全部来自 (https://github.com/MetaCubeX/meta-rules-dat)[https://github.com/MetaCubeX/meta-rules-dat] 官方仓库. 可以自己控制所有配置. 
* **额外提供了最新链式代理配置的模版**, 使用了一个 provider 集中管理需要链式代理的节点.  适合将某一组节点用于出口节点. 比如加速小鸡机场, 或者家宽 ip 要求
* **完美支持 tailscale 和分流**, 默认兼容 macos 上 tailscale, 将其内部 ip 排除, 可不用改任何 tailscale 的配置并使用其 MagicDNS 功能. 且自动分流其使用的内网网段
* 有且只有400多行, 可以自动自主的更新管理多个订阅和规则集
* 趋近完美的 DNS 防泄漏

## 参考
- [使用 clash 上网时应对 dns 泄露的心得](https://v2ex.com/t/1034325)
- [使用公共 DNS 上网的弊端（一）](https://ephen.me/2017/PublicDns_1/)
- [不良林关于DNS的youtube](https://www.youtube.com/watch?v=50iVDmqzDW8)
